# Generated by Django 4.0.6 on 2022-07-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='me',
            new_name='job',
        ),
    ]
