# Generated by Django 4.0.6 on 2022-07-19 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_rename_me_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
