# Generated by Django 4.0.6 on 2022-07-19 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_alter_job_created_alter_job_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='updated',
        ),
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
