# Generated by Django 4.0.6 on 2022-07-19 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_remove_job_updated_alter_job_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
